### PR TITLE
Upgrade SNAFU to 0.7

### PR DESCRIPTION
**Pull request by shepmaster**

### CODE REVIEW

**Review by khrs — COMMENTED** [review]
Any reason for "Snafu" suffix in error names?

**Comment by shepmaster** [comment]
You can see the rationale on the [forum post](https://users.rust-lang.org/t/snafu-0-7-released/69766). TL;DR — having the context selectors have the same name as the enum variants proved to be one of the most complicated parts for newcomers to SNAFU to understand and caused strange compiler errors. 

If you are a fan of the old style, you can disable the suffixes completely via `#[snafu(context(suffix(false)))]`

**Comment by khrs** [comment]
Thank you.

**Comment by shepmaster** [comment]
Thanks for using SNAFU!

**Pull request merged**
